-- ============================================================
--  DATA: DATOS SINTÉTICOS COHERENTES
--  Base de Datos: Sistema de Gestión de Torneos de Videojuegos
-- ============================================================
BEGIN;

-- ============================================================
-- 1. EQUIPOS (10, sin capitán — dependencia circular con Jugador)
-- ============================================================
INSERT INTO Equipo (nombre, fecha_creacion) VALUES
    ('Alpha Wolves',   '2023-01-15 10:00:00'),
    ('Omega Force',    '2022-06-20 14:30:00'),
    ('Phoenix Rising', '2023-03-10 09:15:00'),
    ('Dragon Squad',   '2022-09-05 16:00:00'),
    ('Shadow Ninjas',  '2023-02-28 11:45:00'),
    ('Nova Stars',     '2022-11-14 13:00:00'),
    ('Titan Clash',    '2023-04-01 08:30:00'),
    ('Vortex Team',    '2022-08-22 17:20:00'),
    ('Blaze Gaming',   '2023-05-17 12:00:00'),
    ('Ghost Protocol', '2022-12-30 15:45:00');

-- ============================================================
-- 2. JUGADORES (50 en total, 5 por equipo)
-- ============================================================
INSERT INTO Jugador (id_equipo, gamertag, nombre_real, email, fecha_nacimiento, pais_origen) VALUES
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Alpha Wolves'),'xAlphaLead','Carlos Mendoza','carlos.mendoza@alphawolves.gg','2000-04-12','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Alpha Wolves'),'xAlphaFrag','Diego Romero','diego.romero@alphawolves.gg','2001-07-23','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Alpha Wolves'),'xAlphaAim','Felipe Castro','felipe.castro@alphawolves.gg','1999-11-05','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Alpha Wolves'),'xAlphaTank','Martin Lopez','martin.lopez@alphawolves.gg','2002-03-18','Colombia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Alpha Wolves'),'xAlphaSnipe','Sebastian Torres','sebastian.torres@alphawolves.gg','2000-09-30','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Omega Force'),'OmegaCaptain','Rodrigo Silva','rodrigo.silva@omegaforce.gg','1999-05-14','Brasil'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Omega Force'),'OmegaStrike','Lucas Oliveira','lucas.oliveira@omegaforce.gg','2001-02-28','Brasil'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Omega Force'),'OmegaFlash','Andres Herrera','andres.herrera@omegaforce.gg','2000-08-17','Mexico'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Omega Force'),'OmegaBlast','Pablo Vargas','pablo.vargas@omegaforce.gg','1998-12-03','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Omega Force'),'OmegaGhost','Mateo Gonzalez','mateo.gonzalez@omegaforce.gg','2002-06-25','Uruguay'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Phoenix Rising'),'PhoenixBoss','Alejandro Ruiz','alejandro.ruiz@phoenixrising.gg','2001-01-09','Mexico'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Phoenix Rising'),'PhoenixFire','Camilo Morales','camilo.morales@phoenixrising.gg','2000-10-22','Colombia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Phoenix Rising'),'PhoenixAsh','Roberto Diaz','roberto.diaz@phoenixrising.gg','1999-07-14','Peru'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Phoenix Rising'),'PhoenixWing','Ignacio Perez','ignacio.perez@phoenixrising.gg','2002-04-07','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Phoenix Rising'),'PhoenixRise','Gabriel Santos','gabriel.santos@phoenixrising.gg','2001-09-19','Brasil'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Dragon Squad'),'DragonLord','Emilio Fuentes','emilio.fuentes@dragonsquad.gg','1998-03-25','Venezuela'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Dragon Squad'),'DragonFang','Cesar Reyes','cesar.reyes@dragonsquad.gg','2000-11-08','Ecuador'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Dragon Squad'),'DragonClaw','Omar Castillo','omar.castillo@dragonsquad.gg','2001-05-31','Bolivia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Dragon Squad'),'DragonScale','Nicolas Paredes','nicolas.paredes@dragonsquad.gg','1999-08-16','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Dragon Squad'),'DragonBreath','Tomas Aguilar','tomas.aguilar@dragonsquad.gg','2002-01-27','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Shadow Ninjas'),'ShadowMaster','Javier Moreno','javier.moreno@shadowninja.gg','2000-06-11','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Shadow Ninjas'),'ShadowBlade','Andres Vega','andres.vega@shadowninja.gg','2001-03-24','Colombia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Shadow Ninjas'),'ShadowStep','Miguel Ramos','miguel.ramos@shadowninja.gg','1999-10-15','Mexico'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Shadow Ninjas'),'ShadowStrike','Francisco Jimenez','francisco.jimenez@shadowninja.gg','2002-07-03','Peru'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Shadow Ninjas'),'ShadowFlip','Cristian Munoz','cristian.munoz@shadowninja.gg','2000-02-19','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Nova Stars'),'NovaPrime','Ricardo Leon','ricardo.leon@novastars.gg','2001-09-07','Brasil'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Nova Stars'),'NovaBright','Sebastian Guzman','sebastian.guzman@novastars.gg','1999-12-20','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Nova Stars'),'NovaBlast','Jorge Medina','jorge.medina@novastars.gg','2000-05-14','Colombia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Nova Stars'),'NovaFlash','Alvaro Suarez','alvaro.suarez@novastars.gg','2002-02-28','Venezuela'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Nova Stars'),'NovaCore','Daniel Ortiz','daniel.ortiz@novastars.gg','2001-08-09','Uruguay'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Titan Clash'),'TitanKing','Hernan Espinoza','hernan.espinoza@titanclash.gg','1998-07-30','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Titan Clash'),'TitanCrush','Luis Mendez','luis.mendez@titanclash.gg','2001-04-12','Mexico'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Titan Clash'),'TitanSmash','Eduardo Rios','eduardo.rios@titanclash.gg','2000-11-25','Brasil'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Titan Clash'),'TitanBreak','Vicente Carrasco','vicente.carrasco@titanclash.gg','2002-08-14','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Titan Clash'),'TitanHold','Mauricio Pinto','mauricio.pinto@titanclash.gg','1999-03-07','Ecuador'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Vortex Team'),'VortexSpin','Claudio Navarro','claudio.navarro@vortexteam.gg','2001-06-18','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Vortex Team'),'VortexSwirl','Bryan Flores','bryan.flores@vortexteam.gg','2000-01-31','Peru'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Vortex Team'),'VortexTwist','Axel Ramirez','axel.ramirez@vortexteam.gg','1999-09-22','Bolivia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Vortex Team'),'VortexSurge','Ian Bermudez','ian.bermudez@vortexteam.gg','2002-05-08','Colombia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Vortex Team'),'VortexGale','Kevin Salinas','kevin.salinas@vortexteam.gg','2001-12-03','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Blaze Gaming'),'BlazeFire','Patricio Valenzuela','patricio.valenzuela@blazegaming.gg','2000-08-14','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Blaze Gaming'),'BlazeHeat','Ronald Caceres','ronald.caceres@blazegaming.gg','2001-11-27','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Blaze Gaming'),'BlazeFlame','Samuel Araya','samuel.araya@blazegaming.gg','1999-04-09','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Blaze Gaming'),'BlazeScorch','Bastian Vera','bastian.vera@blazegaming.gg','2002-07-20','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Blaze Gaming'),'BlazeEmber','Gonzalo Pizarro','gonzalo.pizarro@blazegaming.gg','2000-02-15','Colombia'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Ghost Protocol'),'GhostAgent','Nicolas Soto','nicolas.soto@ghostprotocol.gg','2001-03-05','Chile'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Ghost Protocol'),'GhostSpec','Maximiliano Cruz','max.cruz@ghostprotocol.gg','1999-10-18','Brasil'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Ghost Protocol'),'GhostPhase','Fernando Ibanez','fernando.ibanez@ghostprotocol.gg','2000-06-29','Mexico'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Ghost Protocol'),'GhostHaunt','Rodrigo Acevedo','rodrigo.acevedo@ghostprotocol.gg','2002-09-12','Argentina'),
    ((SELECT id_equipo FROM Equipo WHERE nombre = 'Ghost Protocol'),'GhostSilent','Jonathan Cordero','jonathan.cordero@ghostprotocol.gg','2001-01-24','Uruguay');

-- ============================================================
-- 3. ASIGNACIÓN DE CAPITANES (primer jugador de cada equipo)
--    La FK es DEFERRABLE INITIALLY DEFERRED: se valida en COMMIT
-- ============================================================
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaLead') WHERE nombre='Alpha Wolves';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaCaptain') WHERE nombre='Omega Force';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixBoss') WHERE nombre='Phoenix Rising';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='DragonLord') WHERE nombre='Dragon Squad';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowMaster') WHERE nombre='Shadow Ninjas';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='NovaPrime') WHERE nombre='Nova Stars';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='TitanKing') WHERE nombre='Titan Clash';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSpin') WHERE nombre='Vortex Team';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='BlazeFire') WHERE nombre='Blaze Gaming';
UPDATE Equipo SET id_capitan=(SELECT id_jugador FROM Jugador WHERE gamertag='GhostAgent') WHERE nombre='Ghost Protocol';

-- ============================================================
-- 4. TORNEOS (3)
-- ============================================================
INSERT INTO Torneo (nombre, videojuego, fecha_inicio, fecha_fin, prize_pool_usd, max_equipos) VALUES
    ('Liga Mundial de Valorant 2025',    'Valorant',          '2025-03-01','2025-03-15', 50000.00, 8),
    ('Copa Latina de League of Legends', 'League of Legends', '2025-05-10','2025-05-30', 30000.00, 6),
    ('Gran Prix de CS2 Chile 2025',      'Counter-Strike 2',  '2025-07-12','2025-07-25', 20000.00, 8);

-- ============================================================
-- 5. SPONSORS (6)
-- ============================================================
INSERT INTO Sponsor (nombre, industria) VALUES
    ('ASUS ROG',       'tecnologia'),
    ('Red Bull',       'bebidas'),
    ('Nike',           'ropa'),
    ('Intel',          'tecnologia'),
    ('Monster Energy', 'bebidas'),
    ('Razer',          'tecnologia');

-- ============================================================
-- 6. INSCRIPCIONES A TORNEOS
--    T1 (Valorant):    8 equipos — CUPO COMPLETO (max_equipos=8)
--    T2 (LoL):         4 equipos  (cupo 6, aún disponible)
--    T3 (CS2):         3 equipos  (cupo 8)
-- ============================================================
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'),'A');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force'),'A');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising'),'A');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad'),'A');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'),'B');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars'),'B');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash'),'B');
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo,grupo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team'),'B');

INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Copa Latina de League of Legends'),(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'));
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Copa Latina de League of Legends'),(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force'));
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Copa Latina de League of Legends'),(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'));
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Copa Latina de League of Legends'),(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars'));

INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Gran Prix de CS2 Chile 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising'));
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Gran Prix de CS2 Chile 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash'));
INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES ((SELECT id_torneo FROM Torneo WHERE nombre='Gran Prix de CS2 Chile 2025'),(SELECT id_equipo FROM Equipo WHERE nombre='Blaze Gaming'));

-- ============================================================
-- 7. AUSPICIOS
-- ============================================================
INSERT INTO Auspicio_Torneo(id_sponsor,id_torneo,monto_usd) VALUES
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='ASUS ROG'),      (SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),    50000.00),
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='Red Bull'),      (SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),    30000.00),
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='Intel'),         (SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),    40000.00),
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='Nike'),          (SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),    20000.00),
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='Monster Energy'),(SELECT id_torneo FROM Torneo WHERE nombre='Copa Latina de League of Legends'), 25000.00),
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='Razer'),         (SELECT id_torneo FROM Torneo WHERE nombre='Copa Latina de League of Legends'), 35000.00),
    ((SELECT id_sponsor FROM Sponsor WHERE nombre='Red Bull'),      (SELECT id_torneo FROM Torneo WHERE nombre='Gran Prix de CS2 Chile 2025'),      20000.00);

-- ============================================================
-- 8. PARTIDAS — Torneo 1 completo (15 partidas)
--    Grupo A: Alpha, Omega, Phoenix, Dragon
--    Grupo B: Shadow, Nova, Titan, Vortex
--    Avanzan: Alpha (1A), Omega (2A), Shadow (1B), Nova (2B)
--    Campeón: Alpha Wolves
-- ============================================================
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Omega Force'),
     '2025-03-01 14:00:00','fase de grupos',16,9);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising'),
     '2025-03-02 14:00:00','fase de grupos',13,7);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad'),
     '2025-03-03 14:00:00','fase de grupos',14,5);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Omega Force'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising'),
     '2025-03-04 14:00:00','fase de grupos',11,8);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Omega Force'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad'),
     '2025-03-05 14:00:00','fase de grupos',12,6);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad'),
     '2025-03-06 14:00:00','fase de grupos',10,8);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars'),
     '2025-03-01 17:00:00','fase de grupos',15,10);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash'),
     '2025-03-02 17:00:00','fase de grupos',13,8);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team'),
     '2025-03-03 17:00:00','fase de grupos',16,7);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash'),
     '2025-03-04 17:00:00','fase de grupos',12,9);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team'),
     '2025-03-05 17:00:00','fase de grupos',14,8);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team'),
     '2025-03-06 17:00:00','fase de grupos',11,9);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars'),
     '2025-03-12 14:00:00','semifinal',13,10);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Omega Force'),
     '2025-03-12 17:00:00','semifinal',12,9);
INSERT INTO Partida(id_torneo,id_equipo_A,id_equipo_B,fecha_hora,fase,puntaje_equipo_A,puntaje_equipo_B) VALUES
    ((SELECT id_torneo FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves'),
     (SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas'),
     '2025-03-15 16:00:00','final',15,12);

-- ============================================================
-- 9. ESTADÍSTICAS INDIVIDUALES (10 jugadores × 15 partidas = 150 filas)
-- ============================================================
-- Partida 1: Alpha Wolves vs Omega Force (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaLead'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaFrag'),3,0,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaAim'),3,0,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaTank'),4,1,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaSnipe'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaCaptain'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaStrike'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaFlash'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaBlast'),2,2,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaGhost'),2,2,4);

-- Partida 2: Alpha Wolves vs Phoenix Rising (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaLead'),1000,0,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaFrag'),4,1,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaAim'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaTank'),4,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaSnipe'),5,2,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixBoss'),1,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixFire'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixAsh'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixWing'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixRise'),3,3,2);

-- Partida 3: Alpha Wolves vs Dragon Squad (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaLead'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaFrag'),4,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaAim'),5,2,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaTank'),5,2,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaSnipe'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonLord'),2,2,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonFang'),2,2,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonClaw'),3,3,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonScale'),3,3,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonBreath'),3,3,1);

-- Partida 4: Omega Force vs Phoenix Rising (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaCaptain'),4,1,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaStrike'),5,2,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaFlash'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaBlast'),3,0,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaGhost'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixBoss'),2,2,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixFire'),3,3,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixAsh'),3,3,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixWing'),1,1,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixRise'),1,1,3);

-- Partida 5: Omega Force vs Dragon Squad (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaCaptain'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaStrike'),5,2,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaFlash'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaBlast'),3,0,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaGhost'),4,1,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonLord'),3,3,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonFang'),3,3,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonClaw'),1,1,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonScale'),1,1,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonBreath'),2,2,1);

-- Partida 6: Phoenix Rising vs Dragon Squad (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixBoss'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixFire'),3,0,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixAsh'),3,0,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixWing'),4,1,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='PhoenixRise'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonLord'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonFang'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonClaw'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonScale'),2,2,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Phoenix Rising') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Dragon Squad')),(SELECT id_jugador FROM Jugador WHERE gamertag='DragonBreath'),2,2,4);

-- Partida 7: Shadow Ninjas vs Nova Stars (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowMaster'),3,0,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowBlade'),4,1,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStep'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStrike'),4,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowFlip'),5,2,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaPrime'),1,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBright'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBlast'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaFlash'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-01 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaCore'),3,3,2);

-- Partida 8: Shadow Ninjas vs Titan Clash (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowMaster'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowBlade'),4,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStep'),5,2,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStrike'),5,2,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowFlip'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanKing'),2,2,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanCrush'),2,2,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanSmash'),3,3,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanBreak'),3,3,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-02 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanHold'),3,3,1);

-- Partida 9: Shadow Ninjas vs Vortex Team (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowMaster'),4,1,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowBlade'),5,2,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStep'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStrike'),3,0,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowFlip'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSpin'),2,2,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSwirl'),3,3,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexTwist'),3,3,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSurge'),1,1,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-03 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexGale'),1,1,3);

-- Partida 10: Nova Stars vs Titan Clash (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaPrime'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBright'),5,2,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBlast'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaFlash'),3,0,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaCore'),4,1,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanKing'),3,3,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanCrush'),3,3,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanSmash'),1,1,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanBreak'),1,1,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-04 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanHold'),2,2,1);

-- Partida 11: Nova Stars vs Vortex Team (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaPrime'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBright'),3,0,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBlast'),3,0,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaFlash'),4,1,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaCore'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSpin'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSwirl'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexTwist'),1,1,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSurge'),2,2,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-05 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexGale'),2,2,4);

-- Partida 12: Titan Clash vs Vortex Team (fase de grupos)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanKing'),3,0,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanCrush'),4,1,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanSmash'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanBreak'),4,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='TitanHold'),5,2,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSpin'),1,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSwirl'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexTwist'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexSurge'),2,2,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-06 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Titan Clash') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Vortex Team')),(SELECT id_jugador FROM Jugador WHERE gamertag='VortexGale'),3,3,2);

-- Partida 13: Alpha Wolves vs Nova Stars (semifinal)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaLead'),4,1,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaFrag'),4,1,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaAim'),5,2,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaTank'),5,2,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaSnipe'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaPrime'),2,2,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBright'),2,2,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaBlast'),3,3,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaFlash'),3,3,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 14:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Nova Stars')),(SELECT id_jugador FROM Jugador WHERE gamertag='NovaCore'),3,3,1);

-- Partida 14: Shadow Ninjas vs Omega Force (semifinal)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowMaster'),4,1,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowBlade'),5,2,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStep'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStrike'),3,0,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowFlip'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaCaptain'),2,2,1);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaStrike'),3,3,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaFlash'),3,3,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaBlast'),1,1,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-12 17:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Omega Force')),(SELECT id_jugador FROM Jugador WHERE gamertag='OmegaGhost'),1,1,3);

-- Partida 15: Alpha Wolves vs Shadow Ninjas (final)
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaLead'),5,2,6);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaFrag'),5,2,5);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaAim'),3,0,4);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaTank'),3,0,8);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='xAlphaSnipe'),4,1,7);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowMaster'),3,3,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowBlade'),3,3,3);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStep'),1,1,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowStrike'),1,1,2);
INSERT INTO Estadistica_Individual(id_partida,id_jugador,kos,restarts,assists) VALUES((SELECT p.id_partida FROM Partida p JOIN Torneo t ON t.id_torneo=p.id_torneo WHERE t.nombre='Liga Mundial de Valorant 2025' AND p.fecha_hora='2025-03-15 16:00:00' AND p.id_equipo_A=(SELECT id_equipo FROM Equipo WHERE nombre='Alpha Wolves') AND p.id_equipo_B=(SELECT id_equipo FROM Equipo WHERE nombre='Shadow Ninjas')),(SELECT id_jugador FROM Jugador WHERE gamertag='ShadowFlip'),2,2,1);

COMMIT;

-- ============================================================
-- 10. CASO DE PRUEBA: Torneo lleno — trigger trg_validar_max_equipos
-- ============================================================
-- 'Liga Mundial de Valorant 2025' tiene max_equipos=8 y ya tiene
-- 8 equipos inscritos. 'Blaze Gaming' intenta inscribirse → FALLA.
-- El bloque DO captura la excepción sin abortar el script.
-- ============================================================
DO $$
DECLARE
    v_t BIGINT;
    v_e BIGINT;
BEGIN
    SELECT id_torneo INTO v_t FROM Torneo WHERE nombre='Liga Mundial de Valorant 2025';
    SELECT id_equipo INTO v_e FROM Equipo  WHERE nombre='Blaze Gaming';

    INSERT INTO Inscripcion_Torneo(id_torneo,id_equipo) VALUES (v_t,v_e);

    RAISE NOTICE 'ERROR: La inscripción debería haber sido rechazada.';
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE '>>> TRIGGER ACTIVADO CORRECTAMENTE <<<';
        RAISE NOTICE 'Equipo "Blaze Gaming" rechazado del torneo "Liga Mundial de Valorant 2025"';
        RAISE NOTICE 'Mensaje: %', SQLERRM;
END;
$$;

-- ============================================================
-- CONSULTAS DE VERIFICACIÓN
-- ============================================================
-- SELECT COUNT(*) FROM Jugador;                  -- 50
-- SELECT COUNT(*) FROM Equipo;                   -- 10
-- SELECT COUNT(*) FROM Torneo;                   -- 3
-- SELECT COUNT(*) FROM Partida;                  -- 15
-- SELECT COUNT(*) FROM Estadistica_Individual;   -- 150
-- SELECT COUNT(*) FROM Inscripcion_Torneo;       -- 15 (8+4+3)
-- SELECT COUNT(*) FROM Sponsor;                  -- 6
-- SELECT COUNT(*) FROM Auspicio_Torneo;          -- 7
--
-- -- Clasificación Torneo 1:
-- SELECT * FROM v_clasificacion_grupos
-- WHERE torneo='Liga Mundial de Valorant 2025'
-- ORDER BY grupo, victorias DESC, puntos_favor DESC;
--
-- -- Top jugadores por KOs:
-- SELECT gamertag,equipo,total_kos,total_assists
-- FROM v_stats_jugador_torneo
-- WHERE torneo='Liga Mundial de Valorant 2025'
-- ORDER BY total_kos DESC LIMIT 10;
--
-- -- Resumen financiero:
-- SELECT * FROM v_resumen_financiero_torneo;
